atari:
  env_wrapper:
    - stable_baselines3.common.atari_wrappers.AtariWrapper
  frame_stack: 4
  policy: 'CnnPolicy'
  n_envs: 8
  n_steps: 256
  n_epochs: 20
  batch_size: 8
  n_timesteps: !!float 5e6
  learning_rate: lin_1.36e-5
  clip_range: lin_0.25
  vf_coef: 0.54
  ent_coef: 5.37e-8
  gae_lambda: 0.85
  gamma: 0.95
  max_grad_norm: 0.5
  policy_kwargs: "dict(net_arch=dict(pi=[64],vf=[64, 64]), activation_fn=nn.ELU, ortho_init=True)"